In [1]:
#My name is Nihal

In [8]:
import pandas as pd
df = pd.read_csv("customers.csv")

In [15]:
df

   customer_id   name  age gender  spend       city
0          101    Sai   23      M  12000  Bangalore
1          102    Anu   29      F  18000  Hyderabad
2          103  Rahul   35      M  25000      Delhi
3          104  Meena   21      F   8000    Chennai

In [16]:
df["spend"].tolist()

[12000, 18000, 25000, 8000]

In [17]:
print(list(df["spend"]))

[12000, 18000, 25000, 8000]

In [11]:
df.loc[0, "name"].upper()

'SAI'

In [5]:
print(df.dtypes)

customer_id    int64
name             str
age            int64
gender           str
spend          int64
city             str
dtype: object

In [7]:
df["spend"] = df["spend"].astype(str)

print(df.dtypes)

customer_id    int64
name             str
age            int64
gender           str
spend            str
city             str
dtype: object

In [ ]:
# From the departmentcolumn,write a program to check weather all the values are string

import pandas as pd
df = pd.read_csv("customers.csv")

all_strings = True
city = df["city"]
# for c in city:
#     if isinstance(c, str):
#         all_strings = True
#     else:
#         all_strings = False

for c in city:
    if not isinstance(c, (str, int, list)):
        all_strings = False
        break



print(all_strings)

True

In [ ]:
string = 'Python is a good programming language'
data = "Get me a data on bell company where month is november"
string1 = string.split()
print(type(string1))
string1.remove("good")
string1 = " ".join(string1)
print(string1)
print(type(string1))

<class 'list'>
Python is a programming language
<class 'str'>

In [3]:
print("1234".isdigit())

True

In [2]:
import pandas as pd
df = pd.read_csv("customers.csv")
df.head()

   customer_id   name  age gender  spend       city
0          101    Sai   23      M  12000  Bangalore
1          102    Anu   29      F  18000  Hyderabad
2          103  Rahul   35      M  25000      Delhi
3          104  Meena   21      F   8000    Chennai
4          105  Nihal   25      M   8000  Hyderabad

In [1]:
!pip install redis

Collecting redis
  Downloading redis-7.1.0-py3-none-any.whl.metadata (12 kB)
Downloading redis-7.1.0-py3-none-any.whl (354 kB)
Installing collected packages: redis
Successfully installed redis-7.1.0

[notice] A new release of pip is available: 24.2 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import redis

r = redis.Redis(
    host="icenrosatl01.rds-a2-np.kob.dell.com",
    port=443,
    password="jzpfYDUlnMSj",
    db=0,
    ssl=True,                  # 🔥 MUST be true
    ssl_cert_reqs=None,        # matches verifyServerCertificate = false
    decode_responses=False,
    socket_timeout=5
)

# Test connection
try:
    print("Connected:", r.ping())
except redis.AuthenticationError:
    print("❌ Authentication failed")
except Exception as e:
    print("❌ Connection error:", e)

Connected: True

In [7]:
def read_key(r, key):
    t = r.type(key)

    if t == "string":
        return r.get(key)
    if t == "hash":
        return r.hgetall(key)
    if t == "list":
        return r.lrange(key, 0, -1)
    if t == "set":
        return list(r.smembers(key))
    if t == "zset":
        return r.zrange(key, 0, -1, withscores=True)

    return None


for key in r.scan_iter(match="*", count=20):
    print(key, "=>", read_key(r, key))

b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 11164]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_677918c6b184d34f6e617a63' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17707]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6857dbd2d31a19c005e49b8c' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17490]' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_6772477412f2927b4cd228ca' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_FRA_FR' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_680087b79ba5092ba34f6842' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_682db4838db5a945465fde19' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67c003a80c6380fae5b3b7e0' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_678cbc9b352d54bc2594af61' => None
b'\xac\xed\x00\x05t\x00\x1cGE2_6944170c188b0d120e8340a6' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17428]' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 37679]' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_67779bb7f5b87734c1a69c96' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_67611ce7257fbe6cf3375e8e' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 42343]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_69231d8fa726594842c21b06' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 70861]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6846a524dd15003e3301614b' => None
b'\xac\xed\x00\x05t\x00\x1aGE1_GLOBAL_INVOICE_USA1_EN' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_68234704eebfdfe75dae6edd' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_682db8dd8db5a945465fe1fe' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_697a554dd145b69d52ad3f26' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_NOR_EN' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_6788c2898357021439195e2a' => None
b'\xac\xed\x00\x05t\x00\x1eGE4_GLOBAL_NOTIFICATION_ITA_IT' => None
b'\xac\xed\x00\x05t\x00\x19GE4_GLOBAL_INVOICE_AUT_DE' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_678df17975eda6a9d6b4a803' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68aff4672fc490c2f284b001' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_FIN_FI' => None
b'\xac\xed\x00\x05t\x00\x1dPERF_67611caf7887da1b3e9a882f' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_6784d1b0bd95791f12f22e7c' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 11873]' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_68c9391ef43ed0bdca4e9559' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_JPN_JA' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_6809cffd02e1a12b053c8345' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_68357eb2a5844db1976fdd3d' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 40474]' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_678ca9ef3fdfbfa9e9afcf58' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_694e59fa6e604b0741f52bb9' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_IND_EN' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_BEL_NL' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 35220]' => None
b'\xac\xed\x00\x05t\x00"DEV1_COMP_693bdec0cbed018dfd6986a1' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_677e19fac9d106b303e52447' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_6788d4620c713dd7163a8272' => None
b'\xac\xed\x00\x05t\x00\x17PERF_GLOBAL_QUOTE_MY_ZH' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_TUR_TR' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68d27988c0a3f30d28eabc59' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_677d4e7d31e1fdc987ba03f7' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_678f5e2cd16ecb5fae5e64f4' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_67b3072fd3f442136b3b94c3' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_67869cd2bd95791f12f2327a' => None
b'\xac\xed\x00\x05t\x00\x17GE1_GLOBAL_QUOTE_DEU_EN' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67a48edf7ceed29f5a8b9759' => None
b'\xac\xed\x00\x05t\x00\x19GE4_GLOBAL_INVOICE_BEL_NL' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 36362]' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_67a48edf7ceed29f5a8b9759' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_69047da7158758afe9c742eb' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_692d5214e764ac585484ebf8' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17422]' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_680b684e02e1a12b053cc2c0' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6824597f483bbcb885aac166' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_68c80bcb1e0bb7e9a0e3118c' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_NZL_EN' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6732ecbdad4340a20c1f47f1' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_69048494158758afe9c745fa' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_678a1c480781b79e8bd71191' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_COL_EN' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_675fc0d3b2025f24d7b521a1' => None
b'dev1::ice_storage_type::SimpleKey [PartsAndLabor, 8769]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_682347befe015226676e1e4d' => None
b'\xac\xed\x00\x05t\x00\x19GE4_GLOBAL_INVOICE_ESP_ES' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_678a271be0fd0482727a5b23' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_678df17975eda6a9d6b4a803' => None
b'ge4::ice_storage_type::SimpleKey [OrderPaymentHeld, 75795]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67da7169b3f5a4372d0f4705' => None
b'ge4::config_by_originator_cfotype_bucode_delivery::-1461298541' => None
b'\xac\xed\x00\x05t\x00\x1eGE4_GLOBAL_NOTIFICATION_IND_EN' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 12406]' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 88246]' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_673ee4dd4da83fee0cf3e17f' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6809ff2602e1a12b053c8f3a' => None
b'dev1::ice_storage_type::SimpleKey [PartsOnly, 6473]' => None
b'\xac\xed\x00\x05t\x00\x1aGE4_GLOBAL_INVOICE_USA2_EN' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_68aae4b50c3614b988a7ecc5' => None
b'\xac\xed\x00\x05t\x00\x18GE1_GLOBAL_ORDER_USA1_EN' => None
b'\xac\xed\x00\x05t\x00\x19GE4_GLOBAL_INVOICE_DNK_DA' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_672b0c233233a0f9962f480f' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_6834b0bc795d15a7ee2e34bd' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_693bdec0cbed018dfd6986a1' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_CZE_CS' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_MEX_ES' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_PER_EN' => None
b'dev1::ice_storage_type::SimpleKey [PartsAndLabor, 16793]' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 43339]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6911a221363991973f87762a' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 36267]' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_6866319eaf4e1193c2cb32e3' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 14016]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_659fd056fb258e0065c9db71' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6720aa68d16cbd692ca13837' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_672c950f9c30fcc03b136d89' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_685529c4a98f5df39c53f6e5' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_674714989f9d553e761374c0' => None
b'\xac\xed\x00\x05t\x00\x19GE2_GLOBAL_SERVICES_GB_EN' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17520]' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_674daa618cca9f459f71639e' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 0]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_690d9ab730c3a4df572ba125' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 0]' => None
b'\xac\xed\x00\x05t\x00\x18GE4_GLOBAL_ORDER_USA1_EN' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 11285]' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17711]' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_67c7f97693481a23ab8660a0' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 36556]' => None
b'\xac\xed\x00\x05t\x00"DIT1_COMP_67d9387fb3f5a4372d0f38a6' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_690b0cd5857652bacd762bb9' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_67601335589bd80bc0105604' => None
b'\xac\xed\x00\x05t\x00\x17PERF_GLOBAL_QUOTE_PH_ZH' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68a85641f22a31f15e0f5316' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_675fc0d3b2025f24d7b521a1' => None
b'\xac\xed\x00\x05t\x00\x1eGE4_GLOBAL_NOTIFICATION_DEU_DE' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_6761230e6c418b0c17e22df0' => None
b'\xac\xed\x00\x05t\x00"DEV1_COMP_693c0086cbed018dfd699520' => None
b'ge4::config_by_originator_cfotype_bucode_delivery::455125901' => None
b'dev1::ice_services_post_processor::962601172' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_68ef959e4b885b7290a69b32' => None
b'\xac\xed\x00\x05t\x00"DIT1_COMP_6846a524dd15003e3301614b' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_6760190c721d02264ee8b89e' => None
b'\xac\xed\x00\x05t\x00\x1cGE1_67ee777b4b2532ef7e2c4632' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 41214]' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 77580]' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_697a6979d145b69d52ad4260' => None
b'\xac\xed\x00\x05t\x00\x1cGE2_695d36a0260ea79eb37af38c' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_6889c69b87e23df934b20d40' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_687764c3c0dca9aabe78c11e' => None
b'\xac\xed\x00\x05t\x00\x19GE4_GLOBAL_INVOICE_IND_EN' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67601335589bd80bc0105604' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_678cbe053fdfbfa9e9afd02d' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_6893079a47e7510ffeab6d7c' => None
b'\xac\xed\x00\x05t\x00\x1eGE4_GLOBAL_NOTIFICATION_JPN_JA' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_6863bf39f11ce0110982ed10' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6887783beec467bf966c4ec9' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68550b28d25dacff2f0dcd73' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 13905]' => None
b'ge4::config_by_originator_cfotype_bucode::1677263031' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 35943]' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_673c71fd3dd33a1ca1fb979c' => None
b'dev1::ice_storage_type::SimpleKey [PartsAndLabor, 0]' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 33246]' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_DEU_DE' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_6783684573e4c14773b1e289' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68dac578757fcc3c5be7c516' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 35253]' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_67443a8225a2b4aa3eb4f4da' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68d98954c50e075477c60bcc' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_6942891aebc41e8d7dd5e3f8' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_677d00db0cb39ea8939388c9' => None
b'\xac\xed\x00\x05t\x00"DIT1_COMP_674daa618cca9f459f71639e' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_COL_EN' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_PHL_EN' => None
b'\xac\xed\x00\x05t\x00\x17PERF_GLOBAL_QUOTE_AU_ZS' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 70455]' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_678ca46a352d54bc2594ad8e' => None
b'\xac\xed\x00\x05t\x00\x18PERF_GLOBAL_QUOTE_ARG_ES' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6760190c721d02264ee8b89e' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_BRA_PT' => None
b'ge4::config_by_originator_cfotype_bucode::1677253324' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 38335]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6858e26ad31a19c005e4ad8a' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 77670]' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_68ef5c665e04d14263d252c4' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68aaea920c3614b988a7ed27' => None
b'\xac\xed\x00\x05t\x00\x1cGE2_696f4deb2879f022297dea34' => None
b'\xac\xed\x00\x05t\x00\x1eGE4_GLOBAL_NOTIFICATION_COL_ES' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_6780e7e6ffa35f4fcfb7a844' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_680b684e02e1a12b053cc2c0' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_677d00db0cb39ea8939388c9' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_68428e8fc3c700e140d91a55' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 36189]' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_ESP_ES' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68d19221c852d38d15ae112d' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_690499a13376f1e705bc9990' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68008085994d658615f2b189' => None
b'\xac\xed\x00\x05t\x00\x1eGE4_GLOBAL_NOTIFICATION_CAN_EN' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_6981cba5eaba0cef3689c7d2' => None
b'\xac\xed\x00\x05t\x00\x1eGE4_GLOBAL_NOTIFICATION_ITA_EN' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_BRA_EN' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_67d9449b05338d8c26d3d970' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_678f37586fc38ba1e7895d5f' => None
b'\xac\xed\x00\x05t\x00"DIT1_COMP_673c553ce40ab521c8372f8d' => None
b'\xac\xed\x00\x05t\x00\x17PERF_GLOBAL_QUOTE_SG_EN' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17622]' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_CAN_FR' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6846867c2bb598d4be7e465b' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17687]' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 37180]' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_68e8a1fa185e8d38ace37833' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17691]' => None
b'\xac\xed\x00\x05t\x00\x1cGE1_67e57454e3de37dc1848654e' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_689bf598d8f8592f21c025a7' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 81381]' => None
b'ge4::config_by_originator_cfotype_bucode::-1296611144' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_67c7f97693481a23ab8660a0' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_677918c6b184d34f6e617a63' => None
b'\xac\xed\x00\x05t\x00\x1eGE4_GLOBAL_NOTIFICATION_ZAF_EN' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6981cba5eaba0cef3689c7d2' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_677cda3a31e1fdc987b9ff39' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67da91d6b3f5a4372d0f5389' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6858de6ad31a19c005e4ab40' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67d9449b05338d8c26d3d970' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68d17bfec852d38d15ae0c3b' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_692d7f0eea1a3ab264537dea' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6809de2702e1a12b053c87d9' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_69821328eaba0cef3689df41' => None
b'ge4::config_by_originator_cfotype_bucode::1677250861' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 36374]' => None
b'\xac\xed\x00\x05t\x00\x17PERF_GLOBAL_QUOTE_NL_ZH' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 36170]' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_67e579c8a59d7499cba5f8db' => None
b'\xac\xed\x00\x05t\x00"DIT1_COMP_67da704005338d8c26d3e41c' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67d91d7eb3f5a4372d0f36f2' => None
b'dev1::ice_storage_type::SimpleKey [PartsAndLabor, 7479]' => None
b'\xac\xed\x00\x05t\x00\x17PERF_GLOBAL_QUOTE_KR_KO' => None
b'ge4::ice_storage_type::SimpleKey [OrderPaymentHeld, 36570]' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_695bbd9d06349cd29e32a08a' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 31968]' => None
b'\xac\xed\x00\x05t\x00\x1cGE1_677cfc2231e1fdc987ba0151' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_6788d4620c713dd7163a8272' => None
b'ge4::configType::GOVT_APPROVAL_CLEARANCE_MODEL' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_6760190c721d02264ee8b89e' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_682347befe015226676e1e4d' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 14017]' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_AUS_EN' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_6784d1b0bd95791f12f22e7c' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_678cbda732d5eafa57c71522' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6874b088f70c20b908cedac4' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67d9387fb3f5a4372d0f38a6' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_6788c2898357021439195e2a' => None
b'ge4::ice_storage_type::SimpleKey [OrderPaymentHeld, 35782]' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_DNK_DA' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 36169]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_678fde271d9c312c049a2ae3' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67d9208e05338d8c26d3d376' => None
b'\xac\xed\x00\x05t\x00\x19GE4_GLOBAL_INVOICE_CHL_ES' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_681995b1edd70382743e6fb8' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6830488d9b0e95a64d77e318' => None
b'\xac\xed\x00\x05t\x00\x18GE4_GLOBAL_ORDER_SGP2_EN' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_682dc8cddbee060a818b9dec' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_67ee777b4b2532ef7e2c4632' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17706]' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_CHL_ES' => None
b'\xac\xed\x00\x05t\x00\x1cGE2_6942b896ebc41e8d7dd5f3c3' => None
b'\xac\xed\x00\x05t\x00"DIT1_COMP_67d922fd05338d8c26d3d47f' => None
b'\xac\xed\x00\x05t\x00\x17PERF_GLOBAL_QUOTE_CL_ES' => None
b'\xac\xed\x00\x05t\x00\x19GE4_GLOBAL_INVOICE_FRA_EN' => None
b'\xac\xed\x00\x05t\x00\x1dPERF_67ee777b4b2532ef7e2c4632' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_678cbda732d5eafa57c71522' => None
b'\xac\xed\x00\x05t\x00\x19DIT1_GLOBAL_QUOTE_SGP1_EN' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_69242bddbe6fc169738ead1d' => None
b'ge4::config_by_originator_cfotype_bucode_delivery::-175680879' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 74497]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_693671648e4bb8fef0db6cee' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_SVK_EN' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_ORDER_ZAF_EN' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68c93d2bd026b36c856ea878' => None
b'\xac\xed\x00\x05t\x00\x17PERF_GLOBAL_QUOTE_CL_EN' => None
b'\xac\xed\x00\x05t\x00"PERF_COMP_678ddfabb4ff673ab79cbe4b' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67b32e0c891534ce0a48d311' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67d3dcbd3f1f8e2a3b541ff7' => None
b'\xac\xed\x00\x05t\x00\x1dDEV2_67eb93f42c738b54b231c24d' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68e611e6a7d59a2402357ff5' => None
b'ge4::ice_storage_type::SimpleKey [OrderPaymentHeld, 34244]' => None
b'\xac\xed\x00\x05t\x00\x19GE4_GLOBAL_INVOICE_TUR_EN' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_6858da49d31a19c005e4a7dd' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17526]' => None
b'\xac\xed\x00\x05t\x00\x1cGE1_6788a7ca8357021439195c8a' => None
b'\xac\xed\x00\x05t\x00\x17GE4_GLOBAL_QUOTE_AUS_EN' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_685a342789efae84c058c3f9' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_68f0cf2aeb6720129f10ec76' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67efb5c637b57b9457425013' => None
b'\xac\xed\x00\x05t\x00!GE2_COMP_690332d13942a60750b41f26' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17480]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_677d4e7d31e1fdc987ba03f7' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_683ec13aa885ac9edd100472' => None
b'\xac\xed\x00\x05t\x00"DEV2_COMP_682d746510b40fcb0fdb73bf' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_682eeda531e30bde2fe22ab7' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 90290]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_678fd335e7c4639260b25ae4' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 35972]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_67d3bac609f98d953872d415' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_68877259f163c738bf36e6b6' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_68e2634938cf9158811c2762' => None
b'ge4::ice_storage_type::SimpleKey [OrderCancellation, 11377]' => None
b'\xac\xed\x00\x05t\x00!GE4_COMP_678b7eb132d5eafa57c70dd1' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_690495f53376f1e705bc9727' => None
b'\xac\xed\x00\x05t\x00\x1cGE4_68da59f0757fcc3c5be7a45c' => None
b'\xac\xed\x00\x05t\x00\x19GE1_GLOBAL_INVOICE_AUS_EN' => None
b'\xac\xed\x00\x05t\x00\x19GE1_GLOBAL_INVOICE_JPN_JA' => None
b'\xac\xed\x00\x05t\x00!GE1_COMP_67eb98732c738b54b231c455' => None
b'ge4::ice_storage_type::SimpleKey [Invoice, 17678]' => None
b'\xac\xed\x00\x05t\x00\x19PERF_GLOBAL_QUOTE_USA1_EN' => None
b'ge4::ice_storage_type::SimpleKey [OrderPaymentHeld, 38031]' => None
b'ge4::ice_storage_type::SimpleKey [OrderAck, 70153]' => None

KeyboardInterrupt:

In [11]:
import json

user = {
    "id": 103,
    "name": "Sai",
    "role": "Engineer"
}

r.set("user:101", json.dumps(user))

True

In [12]:
data = json.loads(r.get("user:101"))
print(data)

{'id': 103, 'name': 'Sai', 'role': 'Engineer'}